### ISSUE TITLE
Caused New World to lock up for me

### ISSUE THREAD

**Issue by nissa-seru** [LordKobra/CobraFX#1]
I was experimenting with various shaders in New World using Reshade 5.6; upon enabling ColorSort.fx, the game window (including the Reshade menu) became unresponsive. This persisted across restarting the game, as well as uninstalling and reinstalling Reshade with the same set of shaders; uninstalling all shaders and reinstalling all of them (with the exception of ColorSort) caused the game to operate normally once more.

**Comment by LordKobra** [comment]
Hello,

there are two reasons coming to my mind: 
1) I have to create a buffer the size of the game window. Some games have the Viewport rescaled very fast and this can cause issues.
2) ColorSort.fx requires some computing power, if your GPU is too weak, it can freeze the game. Before you activate the shader, in the shader settings below the normal ColorSort.fx settings there is a small preprocessor tab, in there, change the value of COLOR_HEIGHT to 256 and see if it works. Then it's pretty sure a performance issue.

**Comment by nissa-seru** [comment]
Thanks! This was actually an incidental finding while I was testing out a
few other shaders (for a different purpose); unfortunately I don't have it
installed anymore due to pruning my install back to the ones that I needed
- just write down the failure mode here in case helpful. As additional data
point, my GPU is a GeForce 3090, hence (2) seems unlikely (or, conversely,
to be an issue that would affect the vast majority of folks.)

**Comment by LordKobra** [comment]
That's reasonable, but sadly i don't own New World, so it would be interesting to hear about the results. 

You don't have to modify the install for this, you can also just download this repo and manually drag the shader  into /game install folder/reshade-shaders/shaders and colorsort_noise.png into /game install folder/reshade-shaders/textures and then make sure YourActivePresetNameHere.ini does not have it listed in 'Techniques = ...' from the previous install. Then it should start, you can change the preprocessor definitions of COLOR_HEIGHT to 256 and only activate afterwards. In the same way the effect can just be deleted from the folder.

**Comment by nissa-seru** [comment]
Sure - I tried the following after doing an uninstall/reinstall of reshade
and deleting the existing preset (since I'm actually not using any shaders
for New World currently after testing things.)

1. Adding COLOR_HEIGHT as 256 to the global preprocessor definitions per
attached pic (no change to initial behavior, hangs the game + Reshade and
it stays hung.)
2. I couldn't find a way to change the settings for ColorSort_Main only
without activating the shader, so tried changing COLOR_HEIGHT definition in
the source per second attached pic - no change to behavior.

Hope this helps!

**Comment by LordKobra** [comment]
Okay, thank you for the results! I will try and replicate the issue.

**Comment by LordKobra** [comment]
Fixed in https://github.com/LordKobra/CobraFX/commit/f38b38676b1f39931a1747198a52d1369380deda
