### ISSUE TITLE
ColorSort.fx crashed in FFXIV

### ISSUE THREAD

**Issue by liuxd17thu** [LordKobra/CobraFX#3]
Hello LordKobra! I found that ColorSort.fx also made Final Fantasy XIV freeze and ran into a DX11 crash, roughly the same as #1 .

Besides, FFXIV Endwalker has a ~3GB official benchmark, so just installing reshade to benchmark and starting it with **Character Creation** will be a good playground for testing.

**Comment by LordKobra** [comment]
Hello, thank you for the report! Some testing has been done and the issue with Colorsort.fx could be a bug in the HLSL compiler. The compiled code changes based on the variable "NoDebugInfo=1" in the ReShade.ini of the game folder and does let the game crash.

It would be very helpful to figure out, if your report falls into the same category. It's a very simple test. Do you currently have "NoDebugInfo" set to 1 and if so, does changing it to 0 stop the crashes?

**Comment by liuxd17thu** [comment]
Thaks a lot! Now ColorSort works fine with `NoDebugInfo=0`. Then I wonder if this has any side effects, since I noticed that ReShade becomes slower when starting up the game and compiling all shaders in my folder.

Besides, another somewhat off-topic question: I do not see a license in this repo. Would you mind if I translated the shaders here into Chinese (mainly the UI texts) and publish them for free?

**Comment by LordKobra** [comment]
I am aware this is more of a workaround than a full solution. Even if it's technically not a fault with Colorsort.fx, it will receive a proper rewriting in the future, which avoids the error.

About the language translation, I'm unsure to do it the way you suggested. No license does usually equal to "All Rights reserved", except for the parts explicitly annotated to other sources. 
There's two issues right now: 1) I don't like the idea of having multiple repositories for maintenance reasons, and 2) i am in the process of rewriting a lot of shaders and also the UI, which means it would need a re-translation again. 
I asked crosire and he replied experimental language support does currently only exist for Nvidia Freestyle support. However, i think i could write some preprocessor code to support multiple languages. The user would then just manually set a preprocessor option in the menu/ini.
I value your idea and effort about the translation and this way you could do a pull request to this repository with the localized version and put your name in the translation credits. Do you think this sounds like a good idea?

**Comment by liuxd17thu** [comment]
> I value your idea and effort about the translation and this way you could do a pull request to this repository with the localized version (once i updated the shaders and added the preprocessor logic) and put your name in the translation credits. Do you think this sounds like a good idea?
I think it is not very urgent to make multi-language support in shader codes, at least for supporting English & Chinese inside a single branch. Due to some connection reason, Chinese Reshade/GShade users often get the app and shaders "offline-pack" from other users instead of downloading with ReShade/Github. In my opinion, only providing Chinese version for them is enough. Still, I agree that the idea is good! I am looking forward to your multi-language framework!

Now I have cloned this repo to local and working on it. Re-translating is not really a problem for me yet.

**Comment by LordKobra** [comment]
Fixed in https://github.com/LordKobra/CobraFX/commit/f38b38676b1f39931a1747198a52d1369380deda
