### ISSUE TITLE
ReShade 6.3.1 failed to compile

### ISSUE THREAD

**Issue by GODVRP** [LordKobra/CobraFX#5]
![resim_2024-10-05_143210695](https://github.com/user-attachments/assets/7ac6e16a-e610-4530-9a92-50ced1dbd494)
![Screenshot_44](https://github.com/user-attachments/assets/afe67c2a-1b0a-4535-9d3c-2e3c0285f07f)
![Screenshot_45](https://github.com/user-attachments/assets/cb2291bf-7fab-490d-9a75-209689615e76)

**Comment by LordKobra** [comment]
Please make sure you have the ReShade.fxh file in the include path. During installation of ReShade, it comes with the standard effects package.

**Comment by LordKobra** [comment]
This is an issue with the ReShade installation and not the shader. Please use the ReShade help forum.
